# Generated by Django 5.2.7 on 2025-11-30 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('governorate', models.CharField(choices=[('alexandria', 'Alexandria (الإسكندرية)'), ('aswan', 'Aswan (أسوان)'), ('asyut', 'Asyut / Assiut (أسيوط)'), ('beheira', 'Beheira (البحيرة)'), ('beni_suef', 'Beni Suef (بني سويف)'), ('cairo', 'Cairo (القاهرة)'), ('dakahlia', 'Dakahlia (الدقهلية)'), ('damietta', 'Damietta (دمياط)'), ('faiyum', 'Faiyum / Fayoum (الفيوم)'), ('gharbia', 'Gharbia (الغربية)'), ('giza', 'Giza (الجيزة)'), ('ismailia', 'Ismailia (الإسماعيلية)'), ('kafr_el_sheikh', 'Kafr El Sheikh (كفر الشيخ)'), ('matrouh', 'Matrouh (مطروح)'), ('minya', 'Minya (المنيا)'), ('monufia', 'Monufia (المنوفية)'), ('new_valley', 'New Valley / Al Wadi Al Jadid (الوادى الجديد)'), ('north_sinai', 'North Sinai (شمال سيناء)'), ('port_said', 'Port Said (بورسعيد)'), ('qalyubia', 'Qalyubia (القليوبية)'), ('qena', 'Qena (قنا)'), ('red_sea', 'Red Sea (البحر الأحمر)'), ('sharqia', 'Sharqia / Al Sharqia (الشرقية)'), ('sohag', 'Sohag (سوهاج)'), ('suez', 'Suez (السويس)'), ('south_sinai', 'South Sinai (جنوب سيناء)'), ('luxor', 'Luxor (الأقصر)')], max_length=30)),
                ('location', models.TextField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('academic_title', models.CharField(max_length=50)),
                ('office_location', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abstractuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abstractuser',),
        ),
    ]
