# Generated by Django 5.2.7 on 2025-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='governorate',
            field=models.CharField(blank=True, choices=[('alexandria', 'Alexandria (الإسكندرية)'), ('aswan', 'Aswan (أسوان)'), ('asyut', 'Asyut / Assiut (أسيوط)'), ('beheira', 'Beheira (البحيرة)'), ('beni_suef', 'Beni Suef (بني سويف)'), ('cairo', 'Cairo (القاهرة)'), ('dakahlia', 'Dakahlia (الدقهلية)'), ('damietta', 'Damietta (دمياط)'), ('faiyum', 'Faiyum / Fayoum (الفيوم)'), ('gharbia', 'Gharbia (الغربية)'), ('giza', 'Giza (الجيزة)'), ('ismailia', 'Ismailia (الإسماعيلية)'), ('kafr_el_sheikh', 'Kafr El Sheikh (كفر الشيخ)'), ('matrouh', 'Matrouh (مطروح)'), ('minya', 'Minya (المنيا)'), ('monufia', 'Monufia (المنوفية)'), ('new_valley', 'New Valley / Al Wadi Al Jadid (الوادى الجديد)'), ('north_sinai', 'North Sinai (شمال سيناء)'), ('port_said', 'Port Said (بورسعيد)'), ('qalyubia', 'Qalyubia (القليوبية)'), ('qena', 'Qena (قنا)'), ('red_sea', 'Red Sea (البحر الأحمر)'), ('sharqia', 'Sharqia / Al Sharqia (الشرقية)'), ('sohag', 'Sohag (سوهاج)'), ('suez', 'Suez (السويس)'), ('south_sinai', 'South Sinai (جنوب سيناء)'), ('luxor', 'Luxor (الأقصر)')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='location',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
