# Generated by Django 5.2.7 on 2025-12-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_abstractuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractuser',
            options={'ordering': ['id']},
        ),
    ]
