# Generated by Django 5.2.7 on 2025-12-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_abstractuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='academic_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='office_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
