# Generated by Django 5.2.7 on 2025-12-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0004_alter_professor_academic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='academics.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.department'),
            preserve_default=False,
        ),
    ]
