# Generated by Django 5.2.7 on 2025-12-09 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('medterm', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('practical', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('total', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment')),
            ],
        ),
    ]
