from django.db import models

class EgyptGovernorate(models.TextChoices):
    ALEXANDRIA     = "alexandria",     "Alexandria (الإسكندرية)"
    ASWAN          = "aswan",          "Aswan (أسوان)"
    ASYUT          = "asyut",          "Asyut / Assiut (أسيوط)"
    BEHEIRA        = "beheira",        "Beheira (البحيرة)"
    BENI_SUEF      = "beni_suef",      "Beni Suef (بني سويف)"
    CAIRO          = "cairo",          "Cairo (القاهرة)"
    DAKAHLIYA      = "dakahlia",       "Dakahlia (الدقهلية)"
    DAMIETTA       = "damietta",       "Damietta (دمياط)"
    FAIYUM         = "faiyum",         "Faiyum / Fayoum (الفيوم)"
    GHARBIA        = "gharbia",        "Gharbia (الغربية)"
    GIZA           = "giza",           "Giza (الجيزة)"
    ISMAILIA       = "ismailia",       "Ismailia (الإسماعيلية)"
    KAFR_EL_SHEIKH = "kafr_el_sheikh", "Kafr El Sheikh (كفر الشيخ)"
    MATROUH        = "matrouh",        "Matrouh (مطروح)"
    MINYA          = "minya",          "Minya (المنيا)"
    MONUFIA        = "monufia",        "Monufia (المنوفية)"
    NEW_VALLEY     = "new_valley",     "New Valley / Al Wadi Al Jadid (الوادى الجديد)"
    NORTH_SINAI    = "north_sinai",    "North Sinai (شمال سيناء)"
    PORT_SAID      = "port_said",      "Port Said (بورسعيد)"
    QALYUBIA       = "qalyubia",       "Qalyubia (القليوبية)"
    QENA           = "qena",           "Qena (قنا)"
    RED_SEA        = "red_sea",        "Red Sea (البحر الأحمر)"
    SHARQIA        = "sharqia",        "Sharqia / Al Sharqia (الشرقية)"
    SOHAG          = "sohag",          "Sohag (سوهاج)"
    SUEZ           = "suez",           "Suez (السويس)"
    SOUTH_SINAI    = "south_sinai",    "South Sinai (جنوب سيناء)"
    LUXOR          = "luxor",          "Luxor (الأقصر)"
