# Generated by Django 5.2.7 on 2025-12-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_semester_department_head_professor_lecture_and_more'),
        ('users', '0005_professor_department_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=30)),
                ('stamptime', models.DateTimeField(auto_now_add=True)),
                ('lecture_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lectureoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
