# Generated by Django 5.2.7 on 2025-12-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_semester_department_head_professor_lecture_and_more'),
        ('users', '0005_professor_department_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('lectureoffering_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academics.lectureoffering')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('lecture_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_session', to='academics.lectureoffering')),
            ],
            bases=('academics.lectureoffering',),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.attendancesession')),
            ],
        ),
    ]
